### ISSUE TITLE
gradle unit tests failing on main for windows on branch dependabot/github_actions/gradle/actions-4.2.0

### ISSUE THREAD

**Issue by andrewb1269** [hiero-ledger/hiero-cryptography#131]
### Description

It appears the gradle unit tests are failing on main branch.

### Steps to reproduce

See output of workflow [Test on windows-2022](https://github.com/hashgraph/hedera-cryptography/actions/runs/11814144657/job/32917622051#logs)

```
> Task :hedera-cryptography-bls:test


  com.hedera.cryptography.bls.BlsAggregationTest X test(Random)

    java.lang.IllegalStateException: Could not initialize provider com.hedera.cryptography.altbn128.spi.AltBn128Provider@1a411233
        at com.hedera.cryptography.bls.BlsAggregationTest.test(BlsAggregationTest.java:33)
    Caused by: java.lang.NullPointerException: resourceStream must not be null
        at com.hedera.cryptography.bls.BlsAggregationTest.test(BlsAggregationTest.java:33)

```

### Hedera network

other

### Version

v0.1.0

### Operating system

Other

**Comment by andrewb1269** [comment]
@mxtartaglia-sl please take a look at this when you get a chance.

It's blocking the following dependency roll: https://github.com/hashgraph/hedera-cryptography/pull/130

**Comment by mxtartaglia-sl** [comment]
@andrewb1269hg taking a look

**Comment by mxtartaglia-sl** [comment]
It seems that the windows compilation failed and the binary is not included in the jar

```
    Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Could not initialize provider com.hedera.cryptography.altbn128.spi.AltBn128Provider@2be818da [in thread "Test worker"]
        at com.hedera.cryptography.tss.impl.Groth21ServiceTest.<clinit>(Groth21ServiceTest.java:43)
```

**Comment by mxtartaglia-sl** [comment]
@andrewb1269hg , I am assigning this back to you.
As we discussed, something is broken in the Windows compile pipeline. Test cases are passing correctly in Linux and Mac (local) environments. I can't help much without a Linux environment.
