### ISSUE TITLE
 bn254 dependencies not statically linked. e.g: GLIBC

### ISSUE THREAD

**Issue by mxtartaglia-sl** [hiero-ledger/hiero-cryptography#145]
@rbarkerSL , @andrewb1269hg 

@Neeharika-Sompalli  reported the following:
```
Nov 25 18:17:00 gcp-daily-abbrev-update-4n-2c-2024-11-25-180934-0-x6gc swirlds-node[1034]: Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/bn25411682311077882590036/bn254: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/bn25411682311077882590036/bn254)
Nov 25 18:17:00 gcp-daily-abbrev-update-4n-2c-2024-11-25-180934-0-x6gc swirlds-node[1034]:         at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
Nov 25 18:17:00 gcp-daily-abbrev-update-4n-2c-2024-11-25-180934-0-x6gc swirlds-node[1034]:         at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
Nov 25 18:17:00 gcp-daily-abbrev-update-4n-2c-2024-11-25-180934-0-x6gc swirlds-node[1034]:         at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
Nov 25 18:17:00 gcp-daily-abbrev-update-4n-2c-2024-11-25-180934-0-x6gc swirlds-node[1034]:         at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
Nov 25 18:17:00 gcp-daily-abbrev-update-4n-2c-2024-11-25-180934-0-x6gc swirlds-node[1034]:         at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
```

according to @nathanklick :
```
This is a build configuration issue with the rust/cargo/zig configuration not statically linking all the dependencies in the final binary when the rust library is built. 
```

**Comment by rbarker-dev** [comment]
https://github.com/rust-cross/cargo-zigbuild/issues/231

**Comment by rbarker-dev** [comment]
#148 fixes this

**Comment by jjohannes** [comment]
Fix in #148 lgtm. Thanks @rbarkerSL. Is this issue resolved with that?

**Comment by rbarker-dev** [comment]
@mxtartaglia-sl I would like to close this ticket as resolved by #148

**Comment by mxtartaglia-sl** [comment]
Yes, agreed, it is working.
Closed by https://github.com/hashgraph/hedera-cryptography/pull/148

**Comment by mxtartaglia-sl** [comment]
Thanks for the fix!
